.\"     Title: WINFF
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: june 14, 2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "WINFF" "1" "june 14, 2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
winff - video and audio batch converter using ffmpeg
.SH "SYNOPSIS"
.HP 6
\fBwinff\fR
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBwinff\fR
command\. This manual page was written for the
Debian(TM)
distribution because the original program does not have a manual page\. Instead, it has documentation pdf format; see below\.
.PP
WinFF is a graphical user interface for the command line video converter ffmpeg\. It runs ffmpeg from the command line\. So, you just pick your files and it does the rest\.
.PP
WinFF doesn\'t actually convert any video files\. It just runs ffmpeg\. Therefore, It will convert any video file that ffmpeg will convert\. Conversely, if ffmpeg will not convert the file, then WinFF will not either\.
.SH "SEE ALSO"
.PP
For more details, you should have a look at the pdf manual, available at /usr/share/doc/winff/winff\.pdf
.SH "AUTHOR"
.PP
This manual page was written by Paul Gevers
<paul@climbing\.nl>
for the
Debian(TM)
system (but may be used by others)\. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 3 or any later version published by the Free Software Foundation\.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\.
.SH "COPYRIGHT"
Copyright \(co 2008 Paul Gevers
.br
